spring.application.name=cursedfate

server.port=${PORT:8080}

spring.lifecycle.timeout-per-shutdown-phase=30s

logging.level.root=INFO
logging.level.com.i.cursedfate=DEBUG
logging.level.org.hibernate=WARN
logging.level.org.springframework=INFO

spring.datasource.url=${DB_URL:jdbc:postgresql://gondola.proxy.rlwy.net:55333/railway}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:vmBOHjoeGKthOGGTkuBgxUOqFzmUHgZX}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

jwt.secret=${JWT_SECRET:2c6f7e8d9a4b1c3d5f6e7d8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8}
jwt.expiration=3600000
